spring:
  application:
    name: springsec-oauth2
  security:
    user:
      name: ${SECURITY_USERNAME:santiagoarh}
      password: ${SECURITY_PASSWORD:santi1234}
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}

logging:
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n'