spring:
    application:
      name: AuthSantiServer
    datasource:
      url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:BANK}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
    jpa:
      show-sql: true
      properties:
        hibernate:
            format_sql: true


server:
  port: ${AS_SERVER_PORT:9000}

logging:
  level:
    org.springframework.security: {SPRING_SECURITY_LOG:TRACE}
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

