spring:
    config:
      import: application-prod.yml
    profiles:
      active: prod
    application:
        name: ${SPRING_APP_NAME:securitybasics}
    devtools:
        add-properties: false
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/BankDB}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:mysql_password}
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${JWK_SET_URI}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}

logging:
  pattern:
    console: '%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n'